# animate3d.py --- 
# 
# Filename: animate3d.py
# Description: 
# Author: Subhasis Ray
# Maintainer: 
# Created: Thu Aug 11 09:49:49 2011 (+0530)
# Version: 
# Last-Updated: Thu Aug 11 09:53:54 2011 (+0530)
#           By: Subhasis Ray
#     Update #: 2
# URL: 
# Keywords: 
# Compatibility: 
# 
# 

# Commentary: 
# 
# Attempt to use vtk for 3D visualization of data from Traub model simulation 
# 
# 

# Change log:
# 
# 
# 

# Code:

from collections import defaultdict
import numpy

import csv
import vtk

class TraubDataHandler(object):
    """Reader for data generated by Traub model."""
    def __init__(self):
        

# 
# animate3d.py ends here
